language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9

before_install:
  ### Set compiler versions
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

  ### Install AMDs OpenCL implementation
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash Tools/Travis-CI/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDKROOT=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH};
      export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
      export LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LIBRARY_PATH};
    fi;

  ### Install H2Lib
  - git clone https://github.com/H2Lib/H2Lib.git
  - cd H2Lib || exit 1
  - make -j2
  - cd ..

script:
  - mkdir -p build
  - cd build || exit 1
  - cmake -DCMAKE_BUILD_TYPE=Debug -DH2INC:PATH=../H2Lib/Library -DH2LINK:PATH=../H2Lib ..
  - make -j2
  - ctest --output-on-failure

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - opencl-headers
    - libblas-dev
    - liblapack-dev
    - gfortran
