
dist: trusty
sudo: required
language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot
      - opencl-headers
      - libblas-dev
      - liblapack-dev
      - gfortran
      - libboost-all-dev
      - gcc-4.9
      - g++-4.9
      - pkg-config
      - libltdl3-dev
      - libhwloc-dev
      - llvm-dev
      - clang
      - libclang-dev
      - ocl-icd-opencl-dev
      - libedit-dev

matrix:
  include:
    - os: linux
      compiler:
        - gcc


before_install:
  ### Set compiler to gcc 4.8
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  ### Install Portable Computing Language
  - if [ $TRAVIS_OS_NAME = "linux" ]; then wget http://portablecl.org/downloads/pocl-0.12.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then tar xzf pocl-0.12.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then cd pocl-0.12; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then CC="clang" CXX="clang++" ./configure; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then CC="clang" CXX="clang++" make; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then CC="clang" CXX="clang++" sudo make install; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then cd ..; fi

before_script:
  ### Install H2Lib
  - git clone https://github.com/H2Lib/H2Lib.git
  - cd H2Lib || exit 1
  - sed -i -e 's/USE_CAIRO=1/\#USE_CAIRO=1/g' options.inc.default
  - sed -i -e 's/#USE_OPENCL=1/\USE_CAIRO=1/g' options.inc.default
  - sed -i -e 's/#define INLINE_PREFIX static extern "C"/#define INLINE_PREFIX inline/g' Library/settings.h
  - sed -i -e 's/\/\*\* @brief Boolean type. \*\//\#ifndef __cplusplus\n\/\*\* @brief Boolean type. \*\//g' Library/settings.h
  - sed -i -e 's/extern const bool false;/extern const bool false;\n\#endif/g' Library/settings.h
  - make -j2
  - cd ..

script:
  - mkdir -p build
  - cd build || exit 1
  - cmake -DCMAKE_BUILD_TYPE=Debug -DH2INC:PATH=/home/travis/build/BenSolus/master-thesis/H2Lib/Library -DH2LINK:PATH=/home/travis/build/BenSolus/master-thesis/H2Lib ..
  - make -j2

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10
