title:              My master thesis
tagline:            Scalable solving of boundary element methods utilizing the
                    Green cross approximation method and GPUs
baseurl:            "/master-thesis"
url:                "https://bensolus.github.io/master-thesis"
markdown:           kramdown
theme:              jekyll-theme-dinky
sass:
    sass_dir:       _sass
excerpt_separator:  <!--more-->
show_downloads:     false
email:              bca@informatik.uni-kiel.de
github_username:    BenSolus
bitbucket_username: BenSolus
