title:              My master thesis
tagline:            An efficient implementation of the Green cross
                    approximation method on GPGPUs
baseurl:            "/master-thesis"
url:                "https://bensolus.github.io/master-thesis"
markdown:           kramdown
theme:              jekyll-theme-dinky
sass:
    sass_dir:       _sass
excerpt_separator:  <!--more-->
show_downloads:     false
email:              bennet.carstensen@gmail.com
github_username:    BenSolus
bitbucket_username: BenSolus
